// Generated by https://quicktype.io

import { IMunicipio } from "./municipio";
import { IProvincia } from "./provincia";

export interface IDireccion {
    idDireccion?:  string;
    calle:         string;
    pais:          string;
    cp:            string;
    provincia:     IProvincia;
    municipio:     IMunicipio;
    esPrincipal:   boolean;
    esFacturacion: boolean;
}



