// Generated by https://quicktype.io

import { IMunicipio } from "./municipio";
import { IProvincia } from "./provincia";

export interface IDireccion {
    calle:         string;
    pais:          string;
    cp:            number;
    provincia:     IProvincia;
    municipio:     IMunicipio;
    esPrincipal:   boolean;
    esFacturacion: boolean;
}



