// Generated by https://quicktype.io


import { ILibro } from "./libro";
import { IDatosPago } from "./datospago";

export interface IPedido {
    idPedido:             string;
    fechaPedido:          Date;
    estadoPedido:         string;
    elementosPedido:      Array< { libroElemento:    ILibro, cantidadElemento: number } >;
    subTotalPedido:       number;
    gastosEnvio:          number;
    totalPedido:          number;
    datosPago:            IDatosPago;
}



